# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'Docker Hub'
        repository: 'bertusv/weatherapi'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        tags: |
          $(tag)
- stage: Provision
  displayName: Provision resources
  dependsOn: Build
  jobs:
    - job: Provision
      displayName: 'Provision resources in Azure'
      pool: 
        vmImage: 'ubuntu-latest'
      variables: 
        - group: Terraform_SP_Vars
      steps:
        - script: |
            set -e 

            terraform init -input=false
            terraform apply -input=false -auto-approve
          name: RunTerraform
          displayName: 'Run Terraform'
          env:
            ARM_Client_ID: $(ARM_Client_ID)
            ARM_Client_Secret: $(ARM_Client_Secret)
            ARM_TENANT_ID: $(ARM_TENANT_ID)
            ARM_SUBSCRIPTION_ID: $(ARM_SUBSCRIPTION_ID)
            TF_VAR_imagebuild: $(tag)
